[phases.setup]
nixPkgs = ["python312"]

[phases.build]
cmds = [
    "cd Backend && pip install -r requirements.txt",
    "cd Backend && python manage.py collectstatic --noinput"
]

[start]
cmd = "cd Backend && python manage.py migrate && gunicorn backend.wsgi --bind 0.0.0.0:$PORT"
